language: java

jdk:
  - openjdk8

branches:
  only:
  - master
  - development

before_script: 
  - cd seip2020_practical_assignments  # enter Maven root directory
  - ls -la # this command just prints the contents of the current working directory.

script: 
  - mvn clean package
    # the coveralls:report is required only for the coveralls coverage service
    # the cobertura:cobertura is optional only for advanced coverage reporting and, if exists, is used by CodeCov 

after_success:
- bash <(curl -s https://codecov.io/bash) -t 9c80464e-0d94-4a8f-a152-305595eaa667
- echo "Hello there!"