language: java

jdk:
  - openjdk8

branches:
  only:
  - master
  - development

before_script: 
  - cd seip2020_practical_assignments  # enter Maven root directory
  - ls -la # this command just prints the contents of the current working directory.

script: 
  - mvn clean package
    # the coveralls:report is required only for the coveralls coverage service
    # the cobertura:cobertura is optional only for advanced coverage reporting and, if exists, is used by CodeCov 

after_success:
  - bash <(curl -s https://codecov.io/bash) -t f7ccf03a-0f81-4d2b-80d0-2a46db272571